version: '3.8'
services:
  telemetry-gen:
    build: ./services/ingestion-go
    environment:
      - STREAM_NAME=Aegis-IoT-Stream
  inference-api:
    build: ./services/inference-api
    ports:
      - "8000:8000"
  localstack:
    image: localstack/localstack # Simulates Kinesis/S3 locally
    ports:
      - "4566:4566"