name: AegisML Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Inference Image
        run: |
          docker build -t aegis-inference:latest ./services/inference-api
          # Push to Amazon ECR (Elastic Container Registry)

      - name: Update Kubernetes Cluster
        run: |
          aws eks update-kubeconfig --name AegisML-Production
          kubectl apply -f infrastructure/k8s/deployment.yaml